#!/bin/bash

#=== main ===#

#53
SIGN_UP_DISPLAY(){
tput cup 0 0
SIGN_UP_BAR
INPUT_ID
}

SIGN_UP_BAR(){
tput cup 1 18
echo "MAIL BOX"
tput cup 0 0
for((i=0;i<20;i++))
do
	for j in 0 42
	do
		tput cup $i $j
		echo "|"
	done
done
tput cup 0 0
for((i=0;i<43;i++))
do
	for j in 0 2 3 19
	do
		tput cup $j $i
		echo "-"
	done
done
INPUT_ID
}
INPUT_ID(){
tput cup 5 2
echo "Input ID: "
tput cup 5 12
read ID
#tput cup 30 0
echo "$ID" >> ID.txt
IDS=`cat ID.txt`
joongbok=$( cat ID.txt | grep -w "$ID" | wc -w )
if [[ $joongbok -lt 2 ]]
then
	INPUT_PS
else
	clear
	tput cup 7 16
	echo "Duplicated!"
	SIGN_UP_DISPLAY
fi

}

INPUT_PS(){
tput cup 7 16
echo "              "
tput cup 7 2
echo "Input password: "
tput cup 7 18
stty -echo
read PS
echo "$PS" >> PS.txt
stty echo
tput cup 9 2
echo "Confirme password: "
tput cup 9 21
stty -echo
read RPS
echo "$RPS" >> RPS.txt
stty echo
if [[ $PS -ne $RPS ]]
then
	tput cup 11 5
	echo "Input password have to"
	tput cup 12 5
	echo "be same with Confirme password!"
	INPUT_PS
elif [[ $PS -eq $RPS ]]
then
	tput cup 11 5
	echo "                      "
	tput cup 12 5
	echo "                               "
	SIGN_OK
fi
}

SIGN_OK(){
tput cup 12 16
echo "*sign up?*"
tput cup 14 15
echo "yes"
tput cup 14 25
echo "no"
while true
do
	SIGN_KEY
done
}

SIGN_KEY(){
tput cup 20 0
read -n 3 key
if [[ "${key}" = "[C" ]]
then
	yesorno=1
	tput cup 14 13
	echo " "
	tput cup 14 23
	echo ">"
elif [[ "${key}" = "[D" ]]
then
	yesorno=2
	tput cup 14 23
	echo " "
	tput cup 14 13
	echo ">"
elif [[ "${key}" = "" ]]
then
	if [[ "${yesorno}" -eq 1 ]]
	then
		clear
#		echo "no"
		cho
	elif [[ "${yesorno}" -eq 2 ]]
	then
		clear
		cho
#		echo "yes"
	else echo ""
	fi
else echo ""
fi
}

SIGN_UP(){
while true
do
SIGN_UP_DISPLAY
done
}

DISPLAY_BAR_FIRST(){
tput cup 0 0
for((i=0;i<13;i++))
do
	for j in 0 42
	do
		tput cup $i $j
		echo "|"
	done
done
tput cup 0 0
for((i=0;i<43;i++))
do
	for j in 0 2 3 12
	do
		tput cup $j $i
		echo "-"
	done
done
tput cup 1 18
echo "MAIL BOX"
tput cup 6 19
echo "sign in"
tput cup 8 19
echo "sign up"
}

first(){
DISPLAY_BAR_FIRST
}

SIGN_IN(){
tput cup 0 0
for((i=0;i<13;i++))
do
        for j in 0 42
        do
                tput cup $i $j
                echo "|"
        done
done
tput cup 0 0
for((i=0;i<43;i++))
do
        for j in 0 2 3 12
        do
                tput cup $j $i
                echo "-"
        done
done
tput cup 1 18
echo "MAIL BOX"
tput cup 5 2
echo "ID: "
tput cup 5 6
read id
tput cup 7 2
echo "password: "
tput cup 7 12
stty -echo
read ps
stty echo
clear
cho
}

firstkey(){
tput cup 20 0
read -n 3 key
if [[ "${key}" = "[A" ]]
then
	setupdown=1
	clear
	tput cup 6 17
	echo ">"
#	echo "up"
elif [[ "${key}" = "[B" ]]
then
	setupdown=2
	clear
	tput cup 8 17
	echo ">"
#	echo "down"
elif [[ "${key}" = "" ]]
then
#	echo "enter"
	if [[ "${setupdown}" -eq 1 ]]
	then
		clear
		SIGN_IN
	elif [[ "${setupdown}" -eq 2 ]]
	then
		clear
		SIGN_UP
	else echo ""
	fi
else echo ""
fi
}

cho(){
clear
tput cup 6 17
echo ">"
tput cup 30 0
while true
do
first
tput cup 30 0
firstkey
done
}

main(){
clear
#setupdown=1
tput cup 6 17
echo ">"
cho
}
main
